## COPYRIGHT (C) HARRY CLARK 2024
## MOTOROLA 68000 STANDALONE EMULATION LIBRARY

## SET THE DEFAULT TARGET TO ALL (THIS IS FOR EASE OF USE WHEN COMPILING)

.DEFAULT_GOAL := all

## ENABLE A SIMPLE PARALLEL EXECUTION PRAGMATIC FOR FASTER EXECUTION TIMES

MAKEFLAGS += -j$(shell nproc)