/* COPYRIHGT (C) HARRY CLARK 2024 */

/* MOTOROLA 68000 STANDALONE EMULATION LIBRARY */

/* THIS FILE PERTAINS TOWARDSS THE MAIN FUNCTIONALITY SURROUNDING THE UTILITY */
/* OF THE CPU AND IT'S SUBSEQUENT DIRECTIVES AND DEFINES */

/* ANY AND ALL OF THE CORRESPONDING DEFINES AND DECLARATIONS CAN BE */
/* ATTRIBUTED TO THE INFROMATION FOUND HERE: https://www.nxp.com/docs/en/reference-manual/M68000PRM.pdf  */ 

/* NESTED INCLUDES */

#include "68K.h"
#include "68KCONF.h"
#include "common.h"

#ifdef USE_68K

/*===============================================================================*/
/*							68000 MAIN CPU FUNCTIONALIY							 */
/*===============================================================================*/

/* FOLLOWING THE INITIAL DECLARATION OF THE VECTOR TABLE */
/* DISCERN THE RUDIMENTARY AMOUNT OF CPU CYCLES */
/* THE CPU WILL GOVERN OVER THE COURSE OF IT'S RUN TIME */

/* THIS WILL ENCOMPASS THE WIDE BITWISE VARIETY */
/* THROUGH THE MEANS OF EVALUATING THE SIZE OF THE DESIGNATED MEMORY */

/* SEE 1.1 USER PROGRAMMING MODEL https://www.nxp.com/docs/en/reference-manual/M68000PRM.pdf#page=13 */

void INITIALISE_68K_CYCLES()
{
	char* CPU_68K_CYCLES = NULL;

	/* THIS LOOP WILL CHECK FOR EVERY SUBSEQUENT BITWISE */
	/* OPERATION AND EVALUATE IT'S DESIGNATED MEMORY */

	/* THE FIRST CO-EFFICIENT REPRESENTS THE BITWISE LENGTH OF THE OPERATION */
	/* THE SECOND CO-EFFICIENT REPRESENTS THE SIZE OF THE REGISTER */

	for (size_t INDEX = 0; INDEX < sizeof(CPU_68K_CYCLES); INDEX++)
	{	
		switch (INDEX / 16)
		{
			case 0:
				CPU_68K_CYCLES[INDEX] += (int)M68K_LOW_BITMASK;
				break;

			case 1:
				CPU_68K_CYCLES[INDEX] += (int)M68K_MID_BITMASK;
				break;

			case 2:
				CPU_68K_CYCLES[INDEX] += (int)M68K_HIGH_BITMASK;
				break;

			default:
				CPU_68K_CYCLES[INDEX] += (int)M68K_MAX_BITMASK;
				break;
		}
	}

	free(CPU_68K_CYCLES);
}

/* ACCESS EACH RESPECTIVE REGISTER FROM THE ENUMERATION */
/* RETURN THE CORRESPONDENCE IN RELATION TO THE SIZE */

/* FOR EASE OF USE WHEN ACCESSING METHODS, I HAVE CREATED A MACRO */
/* TO BE ABLE TO RETURN THE CORRESPONDING ADDRESS VALUE IN RELATION */
/* TO THE INDEXXING OF THE REGISTER ARRAY */

U32* M68K_GET_REGISTERS(struct CPU_68K* CPU, int REGISTER)
{
    /* IF THERE IS NO ACCESSIBLE METHODS */
	/* WE SPECIFICALLY ALLOCATE MEMORY SAID ACCESSING OF REGISTERS */

	/* THE REASON AS TO WHY THERE ARE TWO SEPERATE CASTS IS DUE TO THE FACT */
	/* THAT THE UINTPTR WILL HOUSE THE CORRESPONDING POINTER OF THE RESPECTIVE 32 BIT INTEGER */

	/* IT HAS NOW BEEN UPDATED TO ACCOMODATE FOR THE ACTUAL RETURN OF A 32 BIT INT */
	/* AKIN TO THE MAX SIZE OF THE REGISTERS */

	switch(REGISTER)
	{
		case M68K_D0: return CPU->REGISTER_BASE[0];
		case M68K_D1: return CPU->REGISTER_BASE[1];
		case M68K_D2: return CPU->REGISTER_BASE[2];
		case M68K_D3: return CPU->REGISTER_BASE[3];
		case M68K_D4: return CPU->REGISTER_BASE[4];
		case M68K_D5: return CPU->REGISTER_BASE[5];
		case M68K_D6: return CPU->REGISTER_BASE[6];
		case M68K_D7: return CPU->REGISTER_BASE[7];
		
		case M68K_A0: return CPU->REGISTER_BASE[8];
		case M68K_A1: return CPU->REGISTER_BASE[9];
		case M68K_A2: return CPU->REGISTER_BASE[10];
		case M68K_A3: return CPU->REGISTER_BASE[11];
		case M68K_A4: return CPU->REGISTER_BASE[12];
		case M68K_A5: return CPU->REGISTER_BASE[13];
		case M68K_A6: return CPU->REGISTER_BASE[14];
		case M68K_A7: return CPU->REGISTER_BASE[15];

        case M68K_PC: return (U32*)(uintptr_t)M68K_RETURN_ADDRESS(CPU->PC);

		case M68K_USP:
			return (unsigned*)CPU->S_FLAG;

		case M68K_ISP:
            return CPU->S_FLAG ? (U32*)CPU->STACK_POINTER[4] : (U32*)CPU->REGISTER_BASE[15];

		case M68K_SP:
			return CPU->REGISTER_BASE[15];

		case M68K_SFC:
			return CPU->SOURCE_FUNCTION_COUNTER;

		case M68K_DFC:
			return CPU->DEST_FUNCTION_COUNTER;

		case M68K_VBR:
			return CPU->VBR;

		case M68K_CACR:
			return CPU->CACHE_CONTROL;

		case M68K_CAAR:
			return CPU->CACHE_ADDRESS;

		case M68K_IR:
			return CPU->INDEX_REGISTER;

		default:
			return NULL;
	}
}

#endif
